/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "i2c.h"
#include "i2c_lcd.h"
#include "accel.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	int ret;
	LIS_Data val;
	SystemInit();
	Lcd_Init();
	Lcd_Puts(LCD_LINE1,"LIS3DSH Accel Demo!\r\n");
	LIS_Init();
	DelayMs(1000);
	while(1) {
		if(LIS_IsDataAvail()) {
			val=LIS_GetData();
			sprintf(str, "X=%d, Y=%d, Z=%d\r\n", val.x, val.y, val.z);
			Lcd_WriteByte(LCD_CMD, LCD_DISP_SHIFT_LEFT);
			DelayMs(1000);
			Lcd_Puts(LCD_LINE1,str);
			DelayMs(1000);
			Lcd_WriteByte(LCD_CMD, LCD_CLEAR);
			DelayMs(10);
		}
	}
	return 0;
}







