/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Orange LED -- GPIOD pin 13.
//	1 -- Led On
//	0 -- Led Off

int main(void) {
	SystemInit();

	RCC->AHB1ENR |= BV(3);

	GPIOD->MODER &= ~BV(27);
	GPIOD->MODER |= BV(26);

	GPIOD->OTYPER |= BV(13);

	GPIOD->OSPEEDR |= (BV(27) | BV(26));

	GPIOD->PUPDR &= ~BV(27);
	GPIOD->PUPDR |= BV(26);

	while(1) {

		GPIOD->ODR |= BV(13);

		DelayMs(500);

		GPIOD->ODR &= ~BV(13);

		DelayMs(2000);
	}
	return 0;
}













