/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <uart_menu.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	SystemInit();
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	UartInit(9600);
	while(1){
		int choice;
		UartPuts("Select from menu:\r\n1.Red led On\r\n2.Red led Off\r\n3.Blue led On\r\n4.Blue led Off\r\n\n");
		UartGets(str);
		sscanf(str, "%d", &choice);

		switch(choice){
		case 1: LedOn(LED_RED_PIN);
			UartPuts("Red led is On!\r\n\n");
			break;
		case 2: LedOff(LED_RED_PIN);
			UartPuts("Red led is Off!\r\n");
			break;
		case 3: LedOn(LED_BLUE_PIN);
			UartPuts("Blue led is On!\r\n\n");
			break;
		case 4: LedOff(LED_BLUE_PIN);
			UartPuts("Blue led is Off!\r\n\n");
			break;
		};
	}

	return 0;
}





