/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	LIS_Data val;
	SystemInit();
	UartInit(9600);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	UartPuts("LIS3DSH Accel testing when X-axis,Y-axis value some fixed threshold value\r\n");
	LIS_Init();
	while(1) {
		if(LIS_IsDataAvail())
		{
			val = LIS_GetData();
			sprintf(str, "X=%d, Y=%d, Z=%d\r\n", val.x, val.y, val.z);
			UartPuts(str);
			if(val.x >= 3000)
				LedOn(LED_RED_PIN);
			else if(val.y <= 0)
				LedOn(LED_BLUE_PIN);
			else{
				LedOff(LED_RED_PIN);
				LedOff(LED_BLUE_PIN);
			}


		}
		DelayMs(1000);
	}
	return 0;
}
